# Generated by Django 4.2 on 2023-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Pick_Up_Point', models.TextField()),
                ('Destination', models.TextField()),
                ('Number_of_Passenger', models.CharField(max_length=10)),
                ('Mode_of_Payment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Pick_Up_Point', models.TextField()),
                ('Destination', models.TextField()),
                ('Mode_of_Payment', models.TextField()),
            ],
        ),
    ]
